# Makefile for yhh
# Generated by Hardware Pipeline v2

CC      = gcc
CFLAGS  = -Wall -Wextra -Wpedantic -O2 -std=c11 -Isrc
LDFLAGS =

SRCDIR  = src
OBJDIR  = obj
SOURCES = $(wildcard $(SRCDIR)/*.c)
OBJECTS = $(SOURCES:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
TARGET  = yhh_driver

.PHONY: all clean cppcheck

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $^

$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)

cppcheck:
	cppcheck --enable=all --std=c11 --suppress=missingIncludeSystem \
	         --error-exitcode=1 $(SRCDIR)/

clean:
	rm -rf $(OBJDIR) $(TARGET)
