// TestProject — Unit Tests (Google Test)
// Auto-generated by Hardware Pipeline v2

#include <gtest/gtest.h>

extern "C" { #include "../drivers/hal.h" }
extern "C" { #include "../drivers/hal_regs.h" }

TEST(hal_test, init_returns_ok) {
    // Stub: verify hal init function exists and is callable
    SUCCEED() << "hal driver header included successfully";
}
TEST(hal_regs_test, init_returns_ok) {
    // Stub: verify hal_regs init function exists and is callable
    SUCCEED() << "hal_regs driver header included successfully";
}

