/**
 * @file hal.h
 * @brief Hardware Abstraction Layer for yhh
 * @details Components: Requirements, Requirements, Overview, providing, Cells
 * @note  Auto-generated by Hardware Pipeline v2
 */

#ifndef yhh_HAL_H
#define yhh_HAL_H

#include <stdint.h>
#include <stdbool.h>
#include "hal_regs.h"

/* ================================================================
 * Error codes
 * ================================================================ */
typedef enum {
    HAL_OK            =  0,   /**< Success */
    HAL_ERROR         = -1,   /**< Generic error */
    HAL_BUSY          = -2,   /**< Resource busy */
    HAL_TIMEOUT       = -3,   /**< Operation timed out */
    HAL_INVALID_PARAM = -4,   /**< Invalid parameter */
    HAL_NOT_INIT      = -5,   /**< HAL not initialised */
} hal_status_t;

/* ================================================================
 * Configuration
 * ================================================================ */
typedef struct {
    uint32_t clock_hz;        /**< System clock frequency in Hz */
    uint32_t baud_rate;       /**< UART baud rate */
    uint32_t timeout_ms;      /**< Default operation timeout (ms) */
} hal_config_t;

/* ================================================================
 * Register I/O primitives
 * ================================================================ */

/**
 * @brief  Write a 16-bit value to a device register via UART.
 * @param  addr   Register address (16-bit, bit15=0 for write).
 * @param  value  Value to write.
 * @return HAL_OK on success.
 */
hal_status_t hal_reg_write(uint16_t addr, uint16_t value);

/**
 * @brief  Read a 16-bit value from a device register via UART.
 * @param  addr   Register address (16-bit, bit15=1 for read).
 * @param  value  Pointer to store the read value.
 * @return HAL_OK on success.
 */
hal_status_t hal_reg_read(uint16_t addr, uint16_t *value);

/* ================================================================
 * Lifecycle
 * ================================================================ */
hal_status_t hal_init(const hal_config_t *cfg);
hal_status_t hal_deinit(void);
bool         hal_is_ready(void);

/* ================================================================
 * High-level helpers
 * ================================================================ */

/** @brief Read  */
hal_status_t hal_read_range(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_range(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x40000000(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x40000000(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_before(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_before(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x40000100(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x40000100(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_baud(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_baud(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_control(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_control(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_status(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_status(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_tx(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_tx(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_rx(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_rx(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_tx(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_tx(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_rx(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_rx(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x40000200(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x40000200(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_device(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_device(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_u(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_u(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_u(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_u(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_u(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_u(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_u(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_u(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_u(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_u(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_u(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_u(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_u(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_u(uint16_t value);

#endif /* yhh_HAL_H */