/**
 * @file hal_regs.h
 * @brief Register address map for hv
 * @note  Auto-generated by Hardware Pipeline v2 - do not edit manually.
 */

#ifndef HV_HAL_REGS_H
#define HV_HAL_REGS_H

#include <stdint.h>

/* ================================================================
 * Register Address Map - hv
 * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET
 * ================================================================ */

/** @brief  (access: RW, 32-bit) */
#define REG_OR                             (0x8000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X48                       (0x48U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0000                     (0x0000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00FF                     (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0100                     (0x0100U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01FF                     (0x01ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0200                     (0x0200U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02FF                     (0x02ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0300                     (0x0300U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03FF                     (0x03ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0400                     (0x0400U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04FF                     (0x04ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0500                     (0x0500U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05FF                     (0x05ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0600                     (0x0600U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06FF                     (0x06ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0700                     (0x0700U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07FF                     (0x07ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0800                     (0x0800U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08FF                     (0x08ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0900                     (0x0900U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09FF                     (0x09ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0AFF                     (0x0affU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00                       (0x00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0211                     (0x0211U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02                       (0x02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X11                       (0x11U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01                       (0x01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0001                     (0x0001U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03                       (0x03U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04                       (0x04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0012                     (0x0012U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0048                     (0x0048U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05                       (0x05U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00C8                     (0x00c8U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0004                     (0x0004U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06                       (0x06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07                       (0x07U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0154                     (0x0154U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X014A                     (0x014aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0080                     (0x0080U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0003                     (0x0003U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X57                       (0x57U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X15                       (0x15U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X52                       (0x52U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X80                       (0x80U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X42                       (0x42U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X62                       (0x62U)

/** @brief  (access: RW, 8-bit) */
#define REG_U                              (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4856                     (0x4856U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40000000                 (0x40000000U)

/** @brief  (access: RW, 8-bit) */
#define REG_STATUS                         (0x08U)

/** @brief  (access: RW, 8-bit) */
#define REG_CONTROL                        (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40008000                 (0x40008000U)

/** @brief  (access: RW, 8-bit) */
#define REG_TO                             (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_SPI                            (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_SPI                            (0x10U)

/** @brief  (access: RW, 8-bit) */
#define REG_SPI                            (0x14U)

/** @brief  (access: RW, 8-bit) */
#define REG_TRANSMIT                       (0x18U)

/** @brief  (access: RW, 8-bit) */
#define REG_RECEIVE                        (0x1cU)

/** @brief  (access: RW, 8-bit) */
#define REG_TO                             (0x000000U)

/** @brief  (access: RW, 8-bit) */
#define REG_FOR                            (0x00ffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00000                    (0x00000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFFF                    (0xfffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4C                       (0x4cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4D                       (0x4dU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40                       (0x40U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X41                       (0x41U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40010000                 (0x40010000U)

/** @brief  (access: RW, 8-bit) */
#define REG_TRANSMIT                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_RX                             (0x1cU)

/** @brief  (access: RW, 8-bit) */
#define REG_SLAVE                          (0x20U)

/** @brief  (access: RW, 8-bit) */
#define REG_TX                             (0x24U)

/** @brief  (access: RW, 8-bit) */
#define REG_RX                             (0x28U)

/** @brief  (access: RW, 8-bit) */
#define REG_TRANSFER                       (0x2cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4C                       (0x4cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4D                       (0x4dU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40020000                 (0x40020000U)

/** @brief  (access: RW, 8-bit) */
#define REG_DATA                           (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_RX                             (0x1cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00000000                 (0x00000000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00800000                 (0x00800000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00840000                 (0x00840000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00860000                 (0x00860000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00861000                 (0x00861000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00010000                 (0x00010000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00000100                 (0x00000100U)

/** @brief  (access: RW, 8-bit) */
#define REG_FOR                            (0x01000000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40028000                 (0x40028000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40028008                 (0x40028008U)

/** @brief  (access: RW, 8-bit) */
#define REG_CHANNEL                        (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00FF                     (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01FF                     (0x01ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02FF                     (0x02ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03FF                     (0x03ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04FF                     (0x04ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05FF                     (0x05ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06FF                     (0x06ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07FF                     (0x07ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08FF                     (0x08ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09FF                     (0x09ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0AFF                     (0x0affU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0BFF                     (0x0bffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C00                     (0x0c00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0CFF                     (0x0cffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0DFF                     (0x0dffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0E00                     (0x0e00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0EFF                     (0x0effU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0FFF                     (0x0fffU)

/** @brief  (access: RW, 8-bit) */
#define REG_AND                            (0xffU)

/** @brief  (access: RW, 8-bit) */
#define REG_SYSTEM                         (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_TEMPERATURE                    (0x08ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_POWER                          (0x09ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_FAULT                          (0x0affU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0106                     (0x0106U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0107                     (0x0107U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X050E                     (0x050eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XA5A5                     (0xa5a5U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0501                     (0x0501U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0502                     (0x0502U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0503                     (0x0503U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0601                     (0x0601U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0604                     (0x0604U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0605                     (0x0605U)

/** @brief  (access: RW, 8-bit) */
#define REG_AS                             (0x0602U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0801                     (0x0801U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0802                     (0x0802U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0803                     (0x0803U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_WRITE                          (0x0a04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X5A5A                     (0x5a5aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X7FFF                     (0x7fffU)

/** @brief  (access: RW, 8-bit) */
#define REG_READING                        (0x7fffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0808                     (0x0808U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40030000                 (0x40030000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X200                      (0x200U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0908                     (0x0908U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0910                     (0x0910U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0918                     (0x0918U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X7FFFFFFF                 (0x7fffffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_IN                             (0x0920U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B01                     (0x0b01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B10                     (0x0b10U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFFF                    (0xfffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X80000                    (0x80000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0701                     (0x0701U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0702                     (0x0702U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04C11DB7                 (0x04c11db7U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X007FFFFF                 (0x007fffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XCA5E0F01                 (0xca5e0f01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F04                     (0x0f04U)

/** @brief  (access: RW, 8-bit) */
#define REG_TO                             (0x4000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X7FFF                     (0x7fffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A02                     (0x0a02U)

/** @brief  (access: RW, 8-bit) */
#define REG_IS                             (0x0a02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XC1EA                     (0xc1eaU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XA5                       (0xa5U)

/** @brief  (access: RW, 8-bit) */
#define REG_AS                             (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D01                     (0x0d01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D02                     (0x0d02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D03                     (0x0d03U)

/** @brief  (access: RW, 8-bit) */
#define REG_TO                             (0x1234U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D04                     (0x0d04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D06                     (0x0d06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D06                     (0x0d06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D07                     (0x0d07U)

/** @brief  (access: RW, 8-bit) */
#define REG_AS                             (0x0d08U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D0A                     (0x0d0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C00                     (0x0c00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C04                     (0x0c04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XDEADBEEF                 (0xdeadbeefU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04C11DB7                 (0x04c11db7U)

/** @brief  (access: RW, 8-bit) */
#define REG_TO                             (0xca5e0f01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F04                     (0x0f04U)

/** @brief  (access: RW, 8-bit) */
#define REG_BEFORE                         (0x0f06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFF                       (0xffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X7F                       (0x7fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F                       (0x0fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X050E                     (0x050eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XA5A5                     (0xa5a5U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0FFF                     (0x0fffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09                       (0x09U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D                       (0x0dU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0E                       (0x0eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F                       (0x0fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X12                       (0x12U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X13                       (0x13U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X16                       (0x16U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X17                       (0x17U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X19                       (0x19U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X1A                       (0x1aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X1B                       (0x1bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X1C                       (0x1cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X010000                   (0x010000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X003FFFFF                 (0x003fffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0E                       (0x0eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XA5A5                     (0xa5a5U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F                       (0x0fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00080000                 (0x00080000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X14E0                     (0x14e0U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X19C8                     (0x19c8U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03E8                     (0x03e8U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X22                       (0x22U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X3A98                     (0x3a98U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X23                       (0x23U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0005                     (0x0005U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XC1EA                     (0xc1eaU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X5A5A                     (0x5a5aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01F4                     (0x01f4U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C00                     (0x0c00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0020                     (0x0020U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C00                     (0x0c00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C00                     (0x0c00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C00                     (0x0c00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C00                     (0x0c00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0192                     (0x0192U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D00                     (0x0d00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01204000                 (0x01204000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_UB                             (0xa5U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04C11DB7                 (0x04c11db7U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0002                     (0x0002U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0006                     (0x0006U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0007                     (0x0007U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0008                     (0x0008U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0009                     (0x0009U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0010                     (0x0010U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0011                     (0x0011U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0013                     (0x0013U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0014                     (0x0014U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0015                     (0x0015U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0016                     (0x0016U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0017                     (0x0017U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0018                     (0x0018U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0019                     (0x0019U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0021                     (0x0021U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0022                     (0x0022U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0023                     (0x0023U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0024                     (0x0024U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0025                     (0x0025U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0026                     (0x0026U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0027                     (0x0027U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0028                     (0x0028U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0029                     (0x0029U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0030                     (0x0030U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0031                     (0x0031U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0032                     (0x0032U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0033                     (0x0033U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0034                     (0x0034U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0035                     (0x0035U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0036                     (0x0036U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0037                     (0x0037U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0038                     (0x0038U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0039                     (0x0039U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0040                     (0x0040U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0041                     (0x0041U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0042                     (0x0042U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XCA1B0001                 (0xca1b0001U)

/** @brief  (access: RW, 8-bit) */
#define REG_CALIBRATION                    (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_LO1                            (0x34U)

/** @brief  (access: RW, 8-bit) */
#define REG_LO1                            (0x54U)

/** @brief  (access: RW, 8-bit) */
#define REG_LO2                            (0x74U)

/** @brief  (access: RW, 8-bit) */
#define REG_LO2                            (0x75U)

/** @brief  (access: RW, 8-bit) */
#define REG_LO2                            (0x76U)

/** @brief  (access: RW, 8-bit) */
#define REG_LO2                            (0x78U)

/** @brief  (access: RW, 8-bit) */
#define REG_LO2                            (0x7cU)

/** @brief  (access: RW, 8-bit) */
#define REG_ADC                            (0x82U)

/** @brief  (access: RW, 8-bit) */
#define REG_ADC                            (0x84U)

/** @brief  (access: RW, 8-bit) */
#define REG_ADC                            (0x86U)

/** @brief  (access: RW, 8-bit) */
#define REG_PHASE                          (0x88U)

/** @brief  (access: RW, 8-bit) */
#define REG_VGA                            (0x8aU)

/** @brief  (access: RW, 8-bit) */
#define REG_VGA                            (0x8eU)

/** @brief  (access: RW, 8-bit) */
#define REG_GAIN                           (0x92U)

/** @brief  (access: RW, 8-bit) */
#define REG_CH1                            (0x94U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XD4                       (0xd4U)

/** @brief  (access: RW, 8-bit) */
#define REG_RESERVED                       (0xd4U)

/** @brief  (access: RW, 8-bit) */
#define REG_CRC                            (0xfaU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XF9                       (0xf9U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFE                       (0xfeU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0002D000                 (0x0002d000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00039800                 (0x00039800U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00040000                 (0x00040000U)

/* Common bit-field masks */
#define BIT(n)          (1U << (n))
#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */

#endif /* HV_HAL_REGS_H */