/**
 * @file hal_regs.h
 * @brief Register address map for hh
 * @note  Auto-generated by Hardware Pipeline v2 - do not edit manually.
 */

#ifndef HH_HAL_REGS_H
#define HH_HAL_REGS_H

#include <stdint.h>

/* ================================================================
 * Register Address Map - hh
 * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET
 * ================================================================ */

/** @brief  (access: RW, 32-bit) */
#define REG_OR                             (0x8000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X48                       (0x48U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0000                     (0x0000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00FF                     (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0100                     (0x0100U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01FF                     (0x01ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0200                     (0x0200U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02FF                     (0x02ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0300                     (0x0300U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03FF                     (0x03ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0400                     (0x0400U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04FF                     (0x04ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0500                     (0x0500U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05FF                     (0x05ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0600                     (0x0600U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06FF                     (0x06ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0700                     (0x0700U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07FF                     (0x07ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0800                     (0x0800U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08FF                     (0x08ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0900                     (0x0900U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09FF                     (0x09ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0AFF                     (0x0affU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00                       (0x00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01                       (0x01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0001                     (0x0001U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02                       (0x02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03                       (0x03U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04                       (0x04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05                       (0x05U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06                       (0x06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07                       (0x07U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X2604                     (0x2604U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08                       (0x08U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00000000                 (0x00000000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0036                     (0x0036U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0008                     (0x0008U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09                       (0x09U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0010                     (0x0010U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0020                     (0x0020U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0048                     (0x0048U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0064                     (0x0064U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0004                     (0x0004U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01A0                     (0x01a0U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00C0                     (0x00c0U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0040                     (0x0040U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F00                     (0x0f00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D                       (0x0dU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0E                       (0x0eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F                       (0x0fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X000A                     (0x000aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C80                     (0x0c80U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4000                     (0x4000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X100                      (0x100U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D                       (0x0dU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X57                       (0x57U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X15                       (0x15U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X52                       (0x52U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X80                       (0x80U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X42                       (0x42U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X62                       (0x62U)

/** @brief  (access: RW, 8-bit) */
#define REG_U                              (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_SYSTEM                         (0x0002U)

/** @brief  (access: RW, 8-bit) */
#define REG_SYSTEM                         (0x0003U)

/** @brief  (access: RW, 8-bit) */
#define REG_TEMPERATURE                    (0x0005U)

/** @brief  (access: RW, 8-bit) */
#define REG_POWER                          (0x0006U)

/** @brief  (access: RW, 8-bit) */
#define REG_POWER                          (0x0007U)

/** @brief  (access: RW, 8-bit) */
#define REG_POWER                          (0x0009U)

/** @brief  (access: RW, 8-bit) */
#define REG_PLL                            (0x000aU)

/** @brief  (access: RW, 8-bit) */
#define REG_LNA                            (0x000bU)

/** @brief  (access: RW, 8-bit) */
#define REG_LNA                            (0x000cU)

/** @brief  (access: RW, 8-bit) */
#define REG_RF                             (0x000dU)

/** @brief  (access: RW, 8-bit) */
#define REG_RF                             (0x000eU)

/** @brief  (access: RW, 8-bit) */
#define REG_ERROR                          (0x000fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_SPI                            (0x0101U)

/** @brief  (access: RW, 8-bit) */
#define REG_CHIP                           (0x0102U)

/** @brief  (access: RW, 8-bit) */
#define REG_SPI                            (0x0103U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X1021                     (0x1021U)

/** @brief  (access: RW, 8-bit) */
#define REG_ON                             (0x1234U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XD0                       (0xd0U)

/* Common bit-field masks */
#define BIT(n)          (1U << (n))
#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */

#endif /* HH_HAL_REGS_H */