/**
 * @file hal_regs.h
 * @brief Register address map for gvng
 * @note  Auto-generated by Hardware Pipeline v2 - do not edit manually.
 */

#ifndef GVNG_HAL_REGS_H
#define GVNG_HAL_REGS_H

#include <stdint.h>

/* ================================================================
 * Register Address Map - gvng
 * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET
 * ================================================================ */

/** @brief  (access: RW, 32-bit) */
#define REG_OR                             (0x8000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X40                       (0x40U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X48                       (0x48U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0000                     (0x0000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00FF                     (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0100                     (0x0100U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01FF                     (0x01ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0200                     (0x0200U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02FF                     (0x02ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0300                     (0x0300U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03FF                     (0x03ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0400                     (0x0400U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04FF                     (0x04ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0500                     (0x0500U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05FF                     (0x05ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0600                     (0x0600U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06FF                     (0x06ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0700                     (0x0700U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07FF                     (0x07ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0800                     (0x0800U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08FF                     (0x08ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0900                     (0x0900U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09FF                     (0x09ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0AFF                     (0x0affU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00                       (0x00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4756                     (0x4756U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01                       (0x01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02                       (0x02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03                       (0x03U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04                       (0x04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05                       (0x05U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06                       (0x06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00000000                 (0x00000000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0036                     (0x0036U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0001                     (0x0001U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0020                     (0x0020U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0064                     (0x0064U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0190                     (0x0190U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X1F                       (0x1fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07                       (0x07U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08                       (0x08U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09                       (0x09U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X80                       (0x80U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D                       (0x0dU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0E                       (0x0eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F                       (0x0fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X000000                   (0x000000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X57                       (0x57U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X15                       (0x15U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X52                       (0x52U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X42                       (0x42U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X62                       (0x62U)

/** @brief  (access: RW, 8-bit) */
#define REG_U                              (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_CONTROL                        (0x0101U)

/** @brief  (access: RW, 8-bit) */
#define REG_STATUS                         (0x0102U)

/** @brief  (access: RW, 8-bit) */
#define REG_TX                             (0x0103U)

/** @brief  (access: RW, 8-bit) */
#define REG_RX                             (0x0104U)

/** @brief  (access: RW, 8-bit) */
#define REG_DATA                           (0x0105U)

/** @brief  (access: RW, 8-bit) */
#define REG_ADDRESS                        (0x0201U)

/** @brief  (access: RW, 8-bit) */
#define REG_DATA                           (0x0202U)

/** @brief  (access: RW, 8-bit) */
#define REG_STATUS                         (0x0203U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XD0                       (0xd0U)

/* Common bit-field masks */
#define BIT(n)          (1U << (n))
#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */

#endif /* GVNG_HAL_REGS_H */