# dsf — Qt GUI Application
# Generated by Hardware Pipeline v2
# Qt 5.14.2 | QMake | MinGW 32/64-bit | Windows 10

QT       += core gui widgets serialport
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET   = dsf
TEMPLATE = app
CONFIG  += c++14
DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += \
    main.cpp \
    MainWindow.cpp \
    SerialWorker.cpp \
    DashboardPanel.cpp \
    ControlPanel.cpp \
    LogPanel.cpp \
    SettingsPanel.cpp

HEADERS += \
    MainWindow.h \
    SerialWorker.h \
    DashboardPanel.h \
    ControlPanel.h \
    LogPanel.h \
    SettingsPanel.h

FORMS += \
    MainWindow.ui \
    DashboardPanel.ui \
    ControlPanel.ui \
    LogPanel.ui \
    SettingsPanel.ui

# Default deployment rules
qnx: target.path = /tmp/${TARGET}/bin
else: unix:!android: target.path = /opt/${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
