#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QThread>
#include "SerialWorker.h"

namespace Ui { class MainWindow; }

/**
 * @class MainWindow
 * @brief Application shell for Rf Receiver.
 *
 * Generated by Hardware Pipeline v2 (Qt 5.14.2, QMake, MinGW).
 *
 * Architecture:
 *   .ui files  — all widget layout/creation (Qt Designer)
 *   Panels     — DashboardPanel / ControlPanel / LogPanel / SettingsPanel
 *   SerialWorker — QThread-based QSerialPort I/O
 *   MainWindow — wires signals between panels and worker; no widget creation
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private slots:
    /* SerialWorker -> MainWindow */
    void onDataReceived(const QByteArray &data);
    void onSerialError(const QString &error);

    /* SettingsPanel -> MainWindow -> SerialWorker */
    void onConnectRequested(const QString &port, int baud);
    void onDisconnectRequested();

    /* ControlPanel -> MainWindow -> SerialWorker */
    void onCommandSend(const QString &command);

private:
    void initConnections();

    Ui::MainWindow *ui;
    SerialWorker   *m_worker;
    QThread        *m_workerThread;
};

#endif // MAINWINDOW_H
