/**
 * @file hal.c
 * @brief Hardware Abstraction Layer implementation for yhh
 * @note  Auto-generated by Hardware Pipeline v2
 */

#include "hal.h"
#include <string.h>

/* ================================================================
 * Private state
 * ================================================================ */
static hal_config_t s_cfg    = {0U};
static bool         s_ready  = false;

/* ================================================================
 * Forward declarations (platform-specific - implement per BSP)
 * ================================================================ */
static hal_status_t _uart_write_bytes(const uint8_t *buf, uint16_t len);
static hal_status_t _uart_read_bytes (uint8_t *buf, uint16_t len, uint32_t timeout_ms);

/* ================================================================
 * Register I/O
 * ================================================================ */

hal_status_t hal_reg_write(uint16_t addr, uint16_t value)
{
    if (!s_ready) { return HAL_NOT_INIT; }
    /* UART write frame: [0x57 'W'] [ADDR_MSB] [ADDR_LSB] [DATA_MSB] [DATA_LSB] */
    uint8_t frame[5];
    frame[0] = 0x57U;                          /* 'W' command byte   */
    frame[1] = (uint8_t)((addr  >> 8U) & 0x7FU); /* MSB, bit15=0 write */
    frame[2] = (uint8_t)(addr  & 0xFFU);
    frame[3] = (uint8_t)((value >> 8U) & 0xFFU);
    frame[4] = (uint8_t)(value & 0xFFU);
    return _uart_write_bytes(frame, 5U);
}

hal_status_t hal_reg_read(uint16_t addr, uint16_t *value)
{
    hal_status_t status;
    uint8_t rx[2];
    uint8_t frame[3];
    if (!s_ready)  { return HAL_NOT_INIT; }
    if (value == NULL) { return HAL_INVALID_PARAM; }
    /* UART read frame: [0x52 'R'] [ADDR_MSB|0x80] [ADDR_LSB] */
    frame[0] = 0x52U;                          /* 'R' command byte   */
    frame[1] = (uint8_t)((addr >> 8U) | 0x80U); /* MSB, bit15=1 read  */
    frame[2] = (uint8_t)(addr & 0xFFU);
    status = _uart_write_bytes(frame, 3U);
    if (status != HAL_OK) { return status; }
    status = _uart_read_bytes(rx, 2U, s_cfg.timeout_ms);
    if (status != HAL_OK) { return status; }
    *value = (uint16_t)(((uint16_t)rx[0] << 8U) | (uint16_t)rx[1]);
    return HAL_OK;
}

/* ================================================================
 * Lifecycle
 * ================================================================ */

hal_status_t hal_init(const hal_config_t *cfg)
{
    hal_status_t status;
    uint16_t     scratch_rb;
    if (cfg == NULL) { return HAL_INVALID_PARAM; }
    if (s_ready)     { return HAL_OK; }            /* Idempotent */
    (void)memcpy(&s_cfg, cfg, sizeof(hal_config_t));
    s_ready = true;
    /* Verify register bus: write SCRATCHPAD, read back */
    status = hal_reg_write(REG_SCRATCHPAD, 0xA55AU);
    if (status != HAL_OK) { s_ready = false; return status; }
    status = hal_reg_read((uint16_t)(REG_SCRATCHPAD | 0x8000U), &scratch_rb);
    if (status != HAL_OK) { s_ready = false; return status; }
    if (scratch_rb != 0xA55AU) { s_ready = false; return HAL_ERROR; }
    return HAL_OK;
}

hal_status_t hal_deinit(void)
{
    s_ready = false;
    (void)memset(&s_cfg, 0, sizeof(hal_config_t));
    return HAL_OK;
}

bool hal_is_ready(void)
{
    return s_ready;
}

/* ================================================================
 * High-level register accessors (auto-generated from RDT)
 * ================================================================ */

hal_status_t hal_read_range(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x0100U | 0x8000U), out);
}

hal_status_t hal_write_range(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x0100U & 0x7FFFU), value);
}

hal_status_t hal_read_reg_0x40000000(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x40000000U | 0x8000U), out);
}

hal_status_t hal_write_reg_0x40000000(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x40000000U & 0x7FFFU), value);
}

hal_status_t hal_read_before(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x000000U | 0x8000U), out);
}

hal_status_t hal_write_before(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x000000U & 0x7FFFU), value);
}

hal_status_t hal_read_reg_0x40000100(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x40000100U | 0x8000U), out);
}

hal_status_t hal_write_reg_0x40000100(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x40000100U & 0x7FFFU), value);
}

hal_status_t hal_read_baud(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x00U | 0x8000U), out);
}

hal_status_t hal_write_baud(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x00U & 0x7FFFU), value);
}

hal_status_t hal_read_control(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x02U | 0x8000U), out);
}

hal_status_t hal_write_control(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x02U & 0x7FFFU), value);
}

hal_status_t hal_read_status(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x04U | 0x8000U), out);
}

hal_status_t hal_write_status(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x04U & 0x7FFFU), value);
}

hal_status_t hal_read_tx(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x06U | 0x8000U), out);
}

hal_status_t hal_write_tx(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x06U & 0x7FFFU), value);
}

hal_status_t hal_read_rx(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x08U | 0x8000U), out);
}

hal_status_t hal_write_rx(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x08U & 0x7FFFU), value);
}

hal_status_t hal_read_tx(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x0aU | 0x8000U), out);
}

hal_status_t hal_write_tx(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x0aU & 0x7FFFU), value);
}

hal_status_t hal_read_rx(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x0cU | 0x8000U), out);
}

hal_status_t hal_write_rx(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x0cU & 0x7FFFU), value);
}

hal_status_t hal_read_reg_0x40000200(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x40000200U | 0x8000U), out);
}

hal_status_t hal_write_reg_0x40000200(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x40000200U & 0x7FFFU), value);
}

hal_status_t hal_read_device(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x0aU | 0x8000U), out);
}

hal_status_t hal_write_device(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x0aU & 0x7FFFU), value);
}

hal_status_t hal_read_u(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x03U | 0x8000U), out);
}

hal_status_t hal_write_u(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x03U & 0x7FFFU), value);
}

hal_status_t hal_read_u(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x05U | 0x8000U), out);
}

hal_status_t hal_write_u(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x05U & 0x7FFFU), value);
}

hal_status_t hal_read_u(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x01U | 0x8000U), out);
}

hal_status_t hal_write_u(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x01U & 0x7FFFU), value);
}

hal_status_t hal_read_u(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0xd8U | 0x8000U), out);
}

hal_status_t hal_write_u(uint16_t value)
{
    return hal_reg_write((uint16_t)(0xd8U & 0x7FFFU), value);
}

hal_status_t hal_read_u(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0xc7U | 0x8000U), out);
}

hal_status_t hal_write_u(uint16_t value)
{
    return hal_reg_write((uint16_t)(0xc7U & 0x7FFFU), value);
}

hal_status_t hal_read_u(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x9fU | 0x8000U), out);
}

hal_status_t hal_write_u(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x9fU & 0x7FFFU), value);
}

hal_status_t hal_read_u(uint16_t *out)
{
    return hal_reg_read((uint16_t)(0x0000U | 0x8000U), out);
}

hal_status_t hal_write_u(uint16_t value)
{
    return hal_reg_write((uint16_t)(0x0000U & 0x7FFFU), value);
}

/* ================================================================
 * BSP stubs - implement these for your target platform
 * ================================================================ */

static hal_status_t _uart_write_bytes(const uint8_t *buf, uint16_t len)
{
    /* TODO: implement for your UART peripheral (STM32 HAL, Arduino, etc.) */
    (void)buf; (void)len;
    return HAL_OK;
}

static hal_status_t _uart_read_bytes(uint8_t *buf, uint16_t len, uint32_t timeout_ms)
{
    /* TODO: implement for your UART peripheral */
    (void)buf; (void)len; (void)timeout_ms;
    return HAL_OK;
}