/**
 * @file hal.h
 * @brief Hardware Abstraction Layer for Rf Receiver
 * @details Components: Requirements, Requirements, definitions, is, implemented
 * @note  Auto-generated by Hardware Pipeline v2
 */

#ifndef rf_receiver_HAL_H
#define rf_receiver_HAL_H

#include <stdint.h>
#include <stdbool.h>
#include "hal_regs.h"

/* ================================================================
 * Error codes
 * ================================================================ */
typedef enum {
    HAL_OK            =  0,   /**< Success */
    HAL_ERROR         = -1,   /**< Generic error */
    HAL_BUSY          = -2,   /**< Resource busy */
    HAL_TIMEOUT       = -3,   /**< Operation timed out */
    HAL_INVALID_PARAM = -4,   /**< Invalid parameter */
    HAL_NOT_INIT      = -5,   /**< HAL not initialised */
} hal_status_t;

/* ================================================================
 * Configuration
 * ================================================================ */
typedef struct {
    uint32_t clock_hz;        /**< System clock frequency in Hz */
    uint32_t baud_rate;       /**< UART baud rate */
    uint32_t timeout_ms;      /**< Default operation timeout (ms) */
} hal_config_t;

/* ================================================================
 * Register I/O primitives
 * ================================================================ */

/**
 * @brief  Write a 16-bit value to a device register via UART.
 * @param  addr   Register address (16-bit, bit15=0 for write).
 * @param  value  Value to write.
 * @return HAL_OK on success.
 */
hal_status_t hal_reg_write(uint16_t addr, uint16_t value);

/**
 * @brief  Read a 16-bit value from a device register via UART.
 * @param  addr   Register address (16-bit, bit15=1 for read).
 * @param  value  Pointer to store the read value.
 * @return HAL_OK on success.
 */
hal_status_t hal_reg_read(uint16_t addr, uint16_t *value);

/* ================================================================
 * Lifecycle
 * ================================================================ */
hal_status_t hal_init(const hal_config_t *cfg);
hal_status_t hal_deinit(void);
bool         hal_is_ready(void);

/* ================================================================
 * High-level helpers
 * ================================================================ */

/** @brief Read  */
hal_status_t hal_read_reg_0xb0(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0xb0(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0000(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0000(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x00ff(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x00ff(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0100(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0100(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x01ff(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x01ff(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0200(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0200(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x02ff(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x02ff(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0300(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0300(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x03ff(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x03ff(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0400(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0400(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x04ff(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x04ff(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0800(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0800(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x08ff(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x08ff(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0a00(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0a00(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0a00(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0a00(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x0aff(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x0aff(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x00(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x00(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x5f18(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x5f18(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x01(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x01(uint16_t value);

/** @brief Read  */
hal_status_t hal_read_reg_0x02(uint16_t *out);

/** @brief Write  */
hal_status_t hal_write_reg_0x02(uint16_t value);

#endif /* rf_receiver_HAL_H */