/**
 * @file hal_regs.h
 * @brief Register address map for mn
 * @note  Auto-generated by Hardware Pipeline v2 - do not edit manually.
 */

#ifndef MN_HAL_REGS_H
#define MN_HAL_REGS_H

#include <stdint.h>

/* ================================================================
 * Register Address Map - mn
 * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET
 * ================================================================ */

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4000U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4001U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4002U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4003U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4004U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4005U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4006U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00                       (0x00U)

/** @brief  (access: RW, 8-bit) */
#define REG__5631                          (0x4d4eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04                       (0x04U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x0001U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X10                       (0x10U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x0000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X14                       (0x14U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08                       (0x08U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG__FFFF                          (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG__FFFF                          (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFFFFFF                 (0xffffffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X57                       (0x57U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06                       (0x06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X52                       (0x52U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X15                       (0x15U)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x8000U)

/** @brief  (access: RW, 8-bit) */
#define REG_TX                             (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_INTERRUPT                      (0x18U)

/** @brief  (access: RW, 8-bit) */
#define REG_DATA                           (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X80                       (0x80U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X42                       (0x42U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X62                       (0x62U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4D4E                     (0x4d4eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0010                     (0x0010U)

/** @brief  (access: RW, 8-bit) */
#define REG_0                              (0x0020U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XE0                       (0xe0U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0030                     (0x0030U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0032                     (0x0032U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0100                     (0x0100U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0040                     (0x0040U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0050                     (0x0050U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0054                     (0x0054U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XAA                       (0xaaU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X55                       (0x55U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01                       (0x01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02                       (0x02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03                       (0x03U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05                       (0x05U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07                       (0x07U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09                       (0x09U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B                       (0x0bU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0C                       (0x0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0002                     (0x0002U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0003                     (0x0003U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X4D4E                     (0x4d4eU)

/* Common bit-field masks */
#define BIT(n)          (1U << (n))
#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */

#endif /* MN_HAL_REGS_H */