/**
 * @file hal_regs.h
 * @brief Register address map for receiver
 * @note  Auto-generated by Hardware Pipeline v2 - do not edit manually.
 */

#ifndef RECEIVER_HAL_REGS_H
#define RECEIVER_HAL_REGS_H

#include <stdint.h>

/* ================================================================
 * Register Address Map - receiver
 * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET
 * ================================================================ */

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X54                       (0x54U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0000                     (0x0000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00FF                     (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0100                     (0x0100U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01FF                     (0x01ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0200                     (0x0200U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02FF                     (0x02ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0300                     (0x0300U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03FF                     (0x03ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0400                     (0x0400U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04FF                     (0x04ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0500                     (0x0500U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05FF                     (0x05ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0600                     (0x0600U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06FF                     (0x06ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0AFF                     (0x0affU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00                       (0x00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XA5A5                     (0xa5a5U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XA5A5                     (0xa5a5U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01                       (0x01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0001                     (0x0001U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02                       (0x02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03                       (0x03U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04                       (0x04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05                       (0x05U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X57                       (0x57U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06                       (0x06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X52                       (0x52U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X42                       (0x42U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X15                       (0x15U)

/** @brief  (access: RW, 8-bit) */
#define REG_CONTROL                        (0xff00U)

/** @brief  (access: RW, 8-bit) */
#define REG_STATUS                         (0xff04U)

/** @brief  (access: RW, 8-bit) */
#define REG_TX                             (0xff08U)

/** @brief  (access: RW, 8-bit) */
#define REG_RX                             (0xff0cU)

/** @brief  (access: RW, 8-bit) */
#define REG_BAUD                           (0xff10U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X80                       (0x80U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X62                       (0x62U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0002                     (0x0002U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0010                     (0x0010U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0011                     (0x0011U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0020                     (0x0020U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFF                       (0xffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0030                     (0x0030U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0031                     (0x0031U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0040                     (0x0040U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0050                     (0x0050U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0051                     (0x0051U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XC0                       (0xc0U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFE                       (0xfeU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07                       (0x07U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08                       (0x08U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09                       (0x09U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG__0000                          (0x4000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0104                     (0x0104U)

/* Common bit-field masks */
#define BIT(n)          (1U << (n))
#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */

#endif /* RECEIVER_HAL_REGS_H */