/**
 * @file hal_regs.h
 * @brief Register address map for rx module
 * @note  Auto-generated by Hardware Pipeline v2 - do not edit manually.
 */

#ifndef RX_MODULE_HAL_REGS_H
#define RX_MODULE_HAL_REGS_H

#include <stdint.h>

/* ================================================================
 * Register Address Map - rx module
 * 16-bit UART address: bit15=R/W#, bits[11:8]=BASE, bits[7:0]=OFFSET
 * ================================================================ */

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X1000                     (0x1000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0800                     (0x0800U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0000                     (0x0000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00FF                     (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0100                     (0x0100U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01FF                     (0x01ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0200                     (0x0200U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02FF                     (0x02ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X08FF                     (0x08ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0900                     (0x0900U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X09FF                     (0x09ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0AFF                     (0x0affU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0B00                     (0x0b00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0BFF                     (0x0bffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X00                       (0x00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X5801                     (0x5801U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X01                       (0x01U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X02                       (0x02U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X03                       (0x03U)

/** @brief  (access: RW, 8-bit) */
#define REG_TO                             (0xdeadU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0020                     (0x0020U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0001                     (0x0001U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X57                       (0x57U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X06                       (0x06U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X52                       (0x52U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X80                       (0x80U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X42                       (0x42U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X62                       (0x62U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A00                     (0x0a00U)

/** @brief  (access: RW, 8-bit) */
#define REG_STATUS                         (0x0004U)

/** @brief  (access: RW, 8-bit) */
#define REG_TX                             (0x0008U)

/** @brief  (access: RW, 8-bit) */
#define REG_RX                             (0x000cU)

/** @brief  (access: RW, 8-bit) */
#define REG_BAUD                           (0x0010U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X15                       (0x15U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X8000                     (0x8000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0050                     (0x0050U)

/** @brief  (access: RW, 8-bit) */
#define REG_THAT                           (0x00ffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFFFF                     (0xffffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0002                     (0x0002U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XFF                       (0xffU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0XA000                     (0xa000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X04                       (0x04U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X05                       (0x05U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X07                       (0x07U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0A                       (0x0aU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0D                       (0x0dU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0E                       (0x0eU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X0F                       (0x0fU)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X2000                     (0x2000U)

/** @brief  (access: RW, 8-bit) */
#define REG_REG_0X3000                     (0x3000U)

/* Common bit-field masks */
#define BIT(n)          (1U << (n))
#define REG_RW_FLAG     BIT(15)   /**< Set in address for Read operations */

#endif /* RX_MODULE_HAL_REGS_H */